# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/TaySm/OneDrive/Documents/GitHub/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_bram_ctrl_0_1/VISION_axi_bram_ctrl_0_1.xci
# IP: The module: 'VISION_axi_bram_ctrl_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/TaySm/OneDrive/Documents/GitHub/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_bram_ctrl_0_1/VISION_axi_bram_ctrl_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VISION_axi_bram_ctrl_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/TaySm/OneDrive/Documents/GitHub/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_bram_ctrl_0_1/VISION_axi_bram_ctrl_0_1.xci
# IP: The module: 'VISION_axi_bram_ctrl_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/TaySm/OneDrive/Documents/GitHub/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_bram_ctrl_0_1/VISION_axi_bram_ctrl_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VISION_axi_bram_ctrl_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
