# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_processing_system7_0_0/VISION_processing_system7_0_0.xci
# IP: The module: 'VISION_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_processing_system7_0_0/VISION_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'VISION_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_processing_system7_0_0/VISION_processing_system7_0_0.xci
# IP: The module: 'VISION_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_processing_system7_0_0/VISION_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'VISION_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
