# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/arty_z7_constraints.xdc

# Block Designs: bd/VISION/VISION.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VISION || ORIG_REF_NAME==VISION} -quiet] -quiet

# IP: bd/VISION/ip/VISION_processing_system7_0_0/VISION_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VISION_processing_system7_0_0 || ORIG_REF_NAME==VISION_processing_system7_0_0} -quiet] -quiet

# IP: bd/VISION/ip/VISION_axi_cdma_0_0/VISION_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VISION_axi_cdma_0_0 || ORIG_REF_NAME==VISION_axi_cdma_0_0} -quiet] -quiet

# IP: bd/VISION/ip/VISION_axi_smc_0/VISION_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VISION_axi_smc_0 || ORIG_REF_NAME==VISION_axi_smc_0} -quiet] -quiet

# IP: bd/VISION/ip/VISION_rst_ps7_0_100M_0/VISION_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VISION_rst_ps7_0_100M_0 || ORIG_REF_NAME==VISION_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/VISION/ip/VISION_ps7_0_axi_periph_0/VISION_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VISION_ps7_0_axi_periph_0 || ORIG_REF_NAME==VISION_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/VISION/ip/VISION_driver_block_design_0_0/VISION_driver_block_design_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VISION_driver_block_design_0_0 || ORIG_REF_NAME==VISION_driver_block_design_0_0} -quiet] -quiet

# IP: bd/VISION/ip/VISION_axi_gpio_0_0/VISION_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VISION_axi_gpio_0_0 || ORIG_REF_NAME==VISION_axi_gpio_0_0} -quiet] -quiet

# IP: bd/VISION/ip/VISION_driver_block_design_0_bram_0/VISION_driver_block_design_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VISION_driver_block_design_0_bram_0 || ORIG_REF_NAME==VISION_driver_block_design_0_bram_0} -quiet] -quiet

# IP: bd/VISION/ip/VISION_driver_block_design_0_bram_0_0/VISION_driver_block_design_0_bram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VISION_driver_block_design_0_bram_0_0 || ORIG_REF_NAME==VISION_driver_block_design_0_bram_0_0} -quiet] -quiet

# IP: bd/VISION/ip/VISION_axi_bram_ctrl_0_0/VISION_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VISION_axi_bram_ctrl_0_0 || ORIG_REF_NAME==VISION_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/VISION/ip/VISION_axi_bram_ctrl_0_1/VISION_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VISION_axi_bram_ctrl_0_1 || ORIG_REF_NAME==VISION_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/VISION/ip/VISION_xbar_0/VISION_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VISION_xbar_0 || ORIG_REF_NAME==VISION_xbar_0} -quiet] -quiet

# IP: bd/VISION/ip/VISION_xlslice_0_0/VISION_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VISION_xlslice_0_0 || ORIG_REF_NAME==VISION_xlslice_0_0} -quiet] -quiet

# IP: bd/VISION/ip/VISION_xlslice_1_0/VISION_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VISION_xlslice_1_0 || ORIG_REF_NAME==VISION_xlslice_1_0} -quiet] -quiet

# IP: bd/VISION/ip/VISION_system_ila_0_0/VISION_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VISION_system_ila_0_0 || ORIG_REF_NAME==VISION_system_ila_0_0} -quiet] -quiet

# IP: bd/VISION/ip/VISION_xlslice_2_0/VISION_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VISION_xlslice_2_0 || ORIG_REF_NAME==VISION_xlslice_2_0} -quiet] -quiet

# IP: bd/VISION/ip/VISION_auto_pc_0/VISION_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VISION_auto_pc_0 || ORIG_REF_NAME==VISION_auto_pc_0} -quiet] -quiet

# XDC: bd/VISION/VISION_ooc.xdc
