# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.cache/wt [current_project]
set_property parent.project_path C:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-z7-20:part0:1.0 [current_project]
set_property ip_repo_paths {
  c:/github/Senior-Project-Vivado/ip_repo
  c:/github/Senior-Project-Vivado/INTERRUPT_DRIVER
  c:/github/Senior-Project-Vivado/mean_machine/mean_machine.srcs/sources_1/new
  c:/github/Senior-Project-Vivado/Sout_Module/Sout_Module.srcs/sources_1/new
} [current_project]
set_property ip_output_repo c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/hdl/VISION_wrapper.v
add_files C:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/VISION.bd
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_processing_system7_0_0/VISION_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_cdma_0_0/VISION_axi_cdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_cdma_0_0/VISION_axi_cdma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_10/bd_a547_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_16/bd_a547_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_23/bd_a547_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_30/bd_a547_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_31/bd_a547_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_32/bd_a547_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_33/bd_a547_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_34/bd_a547_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_35/bd_a547_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_24/bd_a547_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_25/bd_a547_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_26/bd_a547_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_27/bd_a547_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_28/bd_a547_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_17/bd_a547_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_18/bd_a547_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_19/bd_a547_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_20/bd_a547_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_21/bd_a547_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_11/bd_a547_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_12/bd_a547_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_13/bd_a547_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_14/bd_a547_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_15/bd_a547_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_2/bd_a547_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_3/bd_a547_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_4/bd_a547_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_5/bd_a547_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_6/bd_a547_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_1/bd_a547_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/bd_0/ip/ip_1/bd_a547_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_rst_ps7_0_100M_0/VISION_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_rst_ps7_0_100M_0/VISION_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_rst_ps7_0_100M_0/VISION_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_driver_block_design_0_0/src/driver_block_design_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_gpio_0_0/VISION_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_gpio_0_0/VISION_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_gpio_0_0/VISION_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_driver_block_design_0_bram_0/VISION_driver_block_design_0_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_driver_block_design_0_bram_0_0/VISION_driver_block_design_0_bram_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_bram_ctrl_0_0/VISION_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_axi_bram_ctrl_0_1/VISION_axi_bram_ctrl_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_xbar_0/VISION_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_auto_pc_0/VISION_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/VISION_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/constrs_1/new/arty_z7_constraints.xdc
set_property used_in_implementation false [get_files C:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/constrs_1/new/arty_z7_constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top VISION_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef VISION_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file VISION_wrapper_utilization_synth.rpt -pb VISION_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
