# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_driver_block_design_0_0/VISION_driver_block_design_0_0.xci
# IP: The module: 'VISION_driver_block_design_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_driver_block_design_0_0/src/driver_block_design_mean_machine_module_0_0/driver_block_design_mean_machine_module_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==driver_block_design_mean_machine_module_0_0 || ORIG_REF_NAME==driver_block_design_mean_machine_module_0_0} -quiet] -quiet

# IP: c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_driver_block_design_0_0/src/driver_block_design_sout_module_0_0/driver_block_design_sout_module_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==driver_block_design_sout_module_0_0 || ORIG_REF_NAME==driver_block_design_sout_module_0_0} -quiet] -quiet

# IP: c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_driver_block_design_0_0/src/driver_block_design_sout_module_1_0/driver_block_design_sout_module_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==driver_block_design_sout_module_1_0 || ORIG_REF_NAME==driver_block_design_sout_module_1_0} -quiet] -quiet

# IP: c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_driver_block_design_0_0/src/driver_block_design_xlconstant_0_0/driver_block_design_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==driver_block_design_xlconstant_0_0 || ORIG_REF_NAME==driver_block_design_xlconstant_0_0} -quiet] -quiet

# IP: c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_driver_block_design_0_0/src/driver_block_design_interrupt_0_0/driver_block_design_interrupt_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==driver_block_design_interrupt_0_0 || ORIG_REF_NAME==driver_block_design_interrupt_0_0} -quiet] -quiet

# XDC: c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_driver_block_design_0_0/src/driver_block_design_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VISION_driver_block_design_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_driver_block_design_0_0/VISION_driver_block_design_0_0.xci
# IP: The module: 'VISION_driver_block_design_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_driver_block_design_0_0/src/driver_block_design_mean_machine_module_0_0/driver_block_design_mean_machine_module_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==driver_block_design_mean_machine_module_0_0 || ORIG_REF_NAME==driver_block_design_mean_machine_module_0_0} -quiet] -quiet

# IP: c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_driver_block_design_0_0/src/driver_block_design_sout_module_0_0/driver_block_design_sout_module_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==driver_block_design_sout_module_0_0 || ORIG_REF_NAME==driver_block_design_sout_module_0_0} -quiet] -quiet

# IP: c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_driver_block_design_0_0/src/driver_block_design_sout_module_1_0/driver_block_design_sout_module_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==driver_block_design_sout_module_1_0 || ORIG_REF_NAME==driver_block_design_sout_module_1_0} -quiet] -quiet

# IP: c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_driver_block_design_0_0/src/driver_block_design_xlconstant_0_0/driver_block_design_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==driver_block_design_xlconstant_0_0 || ORIG_REF_NAME==driver_block_design_xlconstant_0_0} -quiet] -quiet

# IP: c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_driver_block_design_0_0/src/driver_block_design_interrupt_0_0/driver_block_design_interrupt_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==driver_block_design_interrupt_0_0 || ORIG_REF_NAME==driver_block_design_interrupt_0_0} -quiet] -quiet

# XDC: c:/github/Senior-Project-Vivado/Vision_Project/Vision_Project.srcs/sources_1/bd/VISION/ip/VISION_driver_block_design_0_0/src/driver_block_design_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VISION_driver_block_design_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
