# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/TOP_BLOCK/TOP_BLOCK.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_BLOCK || ORIG_REF_NAME==TOP_BLOCK} -quiet] -quiet

# IP: bd/TOP_BLOCK/ip/TOP_BLOCK_processing_system7_0_0/TOP_BLOCK_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_BLOCK_processing_system7_0_0 || ORIG_REF_NAME==TOP_BLOCK_processing_system7_0_0} -quiet] -quiet

# IP: bd/TOP_BLOCK/ip/TOP_BLOCK_axi_gpio_0_0/TOP_BLOCK_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_BLOCK_axi_gpio_0_0 || ORIG_REF_NAME==TOP_BLOCK_axi_gpio_0_0} -quiet] -quiet

# IP: bd/TOP_BLOCK/ip/TOP_BLOCK_ps7_0_axi_periph_0/TOP_BLOCK_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_BLOCK_ps7_0_axi_periph_0 || ORIG_REF_NAME==TOP_BLOCK_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/TOP_BLOCK/ip/TOP_BLOCK_rst_ps7_0_100M_0/TOP_BLOCK_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_BLOCK_rst_ps7_0_100M_0 || ORIG_REF_NAME==TOP_BLOCK_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/TOP_BLOCK/ip/TOP_BLOCK_DisplayDriver_0_0/TOP_BLOCK_DisplayDriver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_BLOCK_DisplayDriver_0_0 || ORIG_REF_NAME==TOP_BLOCK_DisplayDriver_0_0} -quiet] -quiet

# IP: bd/TOP_BLOCK/ip/TOP_BLOCK_xbar_0/TOP_BLOCK_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_BLOCK_xbar_0 || ORIG_REF_NAME==TOP_BLOCK_xbar_0} -quiet] -quiet

# IP: bd/TOP_BLOCK/ip/TOP_BLOCK_auto_pc_0/TOP_BLOCK_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_BLOCK_auto_pc_0 || ORIG_REF_NAME==TOP_BLOCK_auto_pc_0} -quiet] -quiet

# XDC: bd/TOP_BLOCK/TOP_BLOCK_ooc.xdc
